/*Crear una tabla llamada libros */
CREATE TABLE LIBROS(
	ID_LIBRO NUMBER PRIMARY KEY ,
	TITULO VARCHAR2(130)NOT NULL,
	AUTOR VARCHAR2(130) NOT NULL, 
	FECHA_PUBLICACION DATE NOT NULL,
	DISPONIBLE NUMBER(1) NOT NULL
);

/*INSERT*/
INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,FECHA_PUBLICACION,DISPONIBLE) VALUES (1,'ORGULLO Y PREJUCIO','JANE AUSTEN',TO_DATE ('1813-01-28', 'YYYY-MM-DD'),0);
INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,FECHA_PUBLICACION,DISPONIBLE) VALUES (2,'BAJO LA MISMA ESTRELLA' ,'JOHN GREEN',TO_DATE ('2012-01-10','YYYY-MM-DD'),1);
INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,FECHA_PUBLICACION,DISPONIBLE) VALUES (3,'UN PASEO PARA RECORDAR','NICHOLAS SPARKS',TO_DATE('1999-02-23','YYYY-MM-DD'),0);
INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,FECHA_PUBLICACION,DISPONIBLE) VALUES (4,'ANTES DE TI','JOJO MOYES',TO_DATE ('2012-01-05','YYYY-MM-DD'),0);
INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,FECHA_PUBLICACION,DISPONIBLE) VALUES (5,'AFTER','ANNA TODD',TO_DATE('2014-05-06','YYYY-MM-DD'),1);

/*SELECCIONAR TODOS LOS REGISTROS*/
SELECT * FROM LIBROS;

/*MOSTRAR TODOS LOS LIBROS DISPONIBLES*/
SELECT * FROM LIBROS WHERE DISPONIBLE = 1;

/*MOSTRAR TODOS LOS REGISTROS DE TITULO Y AUTOR ALFABETICAMENTE*/
/*EXPLICACION SELECT TITULO,AUTOR FROM LIBROS ORDER BY TITULO ASC ,AUTOR ASC;
 * ESTE SELECT VA A TRAERME EL TITULO Y AUTOR , PERO SI AñADIMOS EL ORDER BY  LO VA A ORDENAR EN FORMA ASCENDENTE*/
SELECT TITULO,AUTOR FROM LIBROS ORDER BY TITULO ASC ,AUTOR ASC;

/*ACTUALIZACION DE UN REGISTRO*/



